'use statics';

export default {
    LOAD: 'LOAD',
    ON_ACTION_CLICK: 'ON_ACTION_CLICK',
    CREATE_GAME_ACTIONS: 'CREATE_GAME-ACTIONS',
    CREATE_NEW_GAME_INSTANCE: 'CREATE_NEW_GAME-INSTANCE',
    CREATE_CURRENT_GAME_INSTANCE: 'CREATE_CURRENT_GAME_INSTANCE',
    UPDATE_GAMES: 'UPDATE_GAMES',
    SAVE_ALL_GAMES:  'SAVE_ALL_GAMES',
    SAVE_CURRENT_GAME: 'SAVE_CURRENT_GAME'
}
